//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralSecureApp.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneralSecureApp.Shared.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string register_email {
            get {
                return ResourceManager.GetString("register_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} must be at least {2} and at max {1} characters long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string register_err1 {
            get {
                return ResourceManager.GetString("register_err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string register_password {
            get {
                return ResourceManager.GetString("register_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string register_register {
            get {
                return ResourceManager.GetString("register_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string register_text1 {
            get {
                return ResourceManager.GetString("register_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use another service to register. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string register_text2 {
            get {
                return ResourceManager.GetString("register_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no external authentication services configured. See this に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string register_text3 {
            get {
                return ResourceManager.GetString("register_text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   article about setting up this ASP.NET application to support logging in via external services に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string register_text4 {
            get {
                return ResourceManager.GetString("register_text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string register_title {
            get {
                return ResourceManager.GetString("register_title", resourceCulture);
            }
        }
    }
}
